import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import './globals.css'
import { Providers } from './providers'
import { Roboto } from 'next/font/google'

export const metadata = {
  title: 'Dinace',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.ico',
  },
}
const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
})

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={roboto.className}>
      <body className="">
        <Providers>
          <Navbar />
          <main className="min-h-[calc(100vh-80px)] dark:bg-[#18202b] dark:text-white bg-white">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
